name: Dependency Updates

on:
  schedule:
    - cron: "0 0 * * 1" # Every Monday
  workflow_dispatch:

jobs:
  dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Run Dependabot
        uses: dependabot/fetch-metadata@v2
