name: Scheduled Maintenance

on:
  schedule:
    - cron: "0 0 * * *" # every midnight
  workflow_dispatch: # 👈 allows manual run

jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Perform maintenance task
        run: echo "Performing scheduled backup and cleanup tasks..."
